import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
// import ModeToggler from "@/components/buttons/ModeToggler";
import { ThemeProvider } from "@/contexts/ThemeContext";
import SettingsAndToggleBtn from "@/components/global/SettingsAndToggleBtn";
import Loading from "@/components/global/Loading";
import Footer from "@/components/main/Footer";

const cairoSans = Cairo({
  variable: "--font-cairo-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ahmad Marzouk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function () {
                try {
                  const theme = localStorage.getItem('theme');
                  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  if (theme === 'dark' || (!theme && prefersDark)) {
                    document.documentElement.classList.add('dark');
                  }
                } catch (_) {}
              })();
            `,
          }}
        />
      </head>
      <body className={` ${cairoSans.variable} antialiased bg-main-bg`}>
        <ThemeProvider>
          <Loading />
          <SettingsAndToggleBtn />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
